### ISSUE TITLE
Add option to jitter initial values

### ISSUE THREAD

**Issue by iantaylor-NOAA** [ss3sim/ss3sim#231] opened 2016-05-31 18:02 UTC
Perhaps something like this already exists, but Andre Punt, during Think Tank by @GwladysLambert on 5/31/16, seems to be on a crusade against starting estimation models with initial values equal to the values used in the operating model. I'm skeptical that this makes much difference, especially for any model that passes diagnostics for convergence. But it might still be useful to add a jitter option. This could either rely on the existing functionality in the starter file of SS or something novel built into an ss3sim function. One issue with the existing function is that the chosen initial values aren't recorded for later examination.

**Comment by kellijohnson-NOAA** [comment] 2019-08-08 17:42
Somewhat of a duplicate of #98, so closing.

**Closed by kellijohnson-NOAA** 2019-08-08 17:42 UTC
Labels: enhancement
