### ISSUE TITLE
Turn off console output as default

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#221] opened 2015-10-08 19:17 UTC
For some reason when I use emacs to run models I don't get console output in serial execution. However, when I switch to RStudio I do get the standard output from running SS3 in the console. I'm not sure what the difference is, but is there a reason this isn't turned off by default? Is it so people can debug issues? If so I don't think `run_ss3sim` is the best place for that -- it really should be done in the console.

See e.g., https://github.com/ss3sim/ss3sim/blob/5f03e36f8ec39d11b0dc1fc05a573ff2564a84d3/R/ss3sim_base.r#L78. 

Any complaints to switch this on by default?

**Comment by kellijohnson** [comment] 2015-10-08 20:17
No problem on my end

On Thu, Oct 8, 2015 at 12:17 PM, Cole Monnahan <notifications@github.com>
wrote:

> For some reason when I use emacs to run models I don't get console output
> in serial execution. However, when I switch to RStudio I do get the
> standard output from running SS3 in the console. I'm not sure what the
> difference is, but is there a reason this isn't turned off by default? Is
> it so people can debug issues? If so I don't think run_ss3sim is the best
> place for that -- it really should be done in the console.
>
> See e.g.,
> https://github.com/ss3sim/ss3sim/blob/5f03e36f8ec39d11b0dc1fc05a573ff2564a84d3/R/ss3sim_base.r#L78.
>
>
> Any complaints to switch this on by default?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ss3sim/ss3sim/issues/221>.
>



-- 
Kelli Faye Johnson
kellifayejohnson@gmail.com

**Comment by seananderson** [comment] 2015-10-14 17:19
No problem here, but this is a Windows-only option that I'm not familiar with. Go ahead and do whatever you think makes sense.

**Comment by colemonnahan** [comment] 2015-10-14 17:26
I implemented this with https://github.com/ss3sim/ss3sim/commit/e89154edaaed6d30afa166f49885874010524ed6 . The only downside I can see is that when developing models the output won't be available in the console for debugging. But really the user should do the testing in a terminal window. Dumping tens of thousands of lines (if not more) to console during a run is not really useful.

A guess a compromise would be to add an argument for printing to console that is turned off by default. I say we go with this until it seems to cause issues. To be honest I also haven't checked how ADMB/SS errors or warnings are passed through with this commit. It could be that they come through fine and then my above point is moot.

**Comment by kellijohnson** [comment] 2015-10-14 18:29
Sorry to reopen this, but the way that it was turned off causes errors in previously written code, and functions inside the package. Before the argument was passed using `...` and now lots of code that I have written that has `show.output.on.cosole` in the `run_ss3sim` call gives me an error for multiple arguments. Can we use something along the lines of:
`
if(!"show.output.on.console" %in% names(list(...))) {
  show.output.on.console <- FALSE
}
system(paste0(paste0(bin, " "), ss_em_options, admb_options),
         invisible = TRUE, ignore.stdout = ignore.stdout, 
         show.output.on.console = show.output.on.console, ...)
`

**Comment by colemonnahan** [comment] 2015-10-14 18:41
Hi @kellijohnson no problem about reopening. Ideally I think we should instead have a top level `run_ss3sim` argument for printing to console, which then works for both Windows and Linux.

Could you just call the argument `show.output.on.console` and then your current code should work?

**Comment by kellijohnson** [comment] 2015-10-14 19:37
I tested it on a windows machine and it seemed to work fine, but I placed the argument in `run_ss3model` with a default of `show.output.on.console = TRUE`. Not sure which function the argument should actually be placed in. @seananderson any advice here?

**Comment by taylori** [comment] 2015-10-14 19:58
This issue may be Emacs-specific rather than windows specific. I've found
that system and shell commands used when running R within Emacs behaved
differently than in other windows implementations of R. I've never
understood this, and behavior may have changed in more recent versions of R
or Emacs, but there are a few r4ss functions with option to use "system"
instead of "shell"
https://github.com/r4ss/r4ss/blob/53da739dc70f7e6cd930b0b3128ea17abc278424/R/SS_profile.R#L261
with the description "Should R call SS using "system" function intead of
"shell". This may be required when running R in Emacs. Default = FALSE."

It looks like ss3sim never uses "shell" but perhaps the issue is still
related.

**Comment by kellijohnson-NOAA** [comment] 2019-08-08 17:47
Everything seems to be working here, but I don't have emacs or linux to test. I am closing this issue and will deal with output if it comes up again.

**Closed by kellijohnson-NOAA** 2019-08-08 17:47 UTC
Labels: enhancement
